### 参数列表
GET {{baseUrl}}/categories/6/attributes?sel=many
Accept: application/json
Authorization: {{token}}

### 添加动态参数或者静态属性
POST {{baseUrl}}/categories/6/attributes
Content-Type: application/json
Authorization: {{token}}

{
  "attr_name": "重量",
  "attr_sel": "many"
}

### 根据 ID 查询参数
GET {{baseUrl}}/categories/6/attributes/3077?attr_sel=many
Accept: application/json
Authorization: {{token}}

### 编辑提交参数
PUT {{baseUrl}}/categories/6/attributes/3077
Content-Type: application/json
Authorization: {{token}}

{
  "attr_name": "版式2",
  "attr_sel": "many"
}

### 删除参数
DELETE {{baseUrl}}/categories/6/attributes/3808
Content-Type: application/json
Authorization: {{token}}
